version: '3.8'
services:
  dev:
    container_name: ecommerce-service
    image: ecommerce-service:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    command: npm run start:debug
    ports:
      - 9000:9000
    depends_on:
      - mongodb
      - redis_db
      - redis-commander
    networks:
      - network-ecommerce-service
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
  mongodb:
    container_name: ecommerce-service-db
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev-ecommerce-service
    networks:
      - network-ecommerce-service
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
  redis_db:
    container_name: redis_db
    image: 'redis:alpine'
    ports:
      - '6395:6379'
    networks:
      - network-ecommerce-service
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis_db:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis_db
    networks:
      - network-ecommerce-service

networks:
  network-ecommerce-service:
volumes:
  mongodb_data_container:
