name: Version

on:
  push:
    branches:
      - develop

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'Update to v')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name 'GitHub Actions'
      - run: git config --global user.email 'arielopez229422@gmail.com'
      - run: npm version minor -m "Update version to v%s"
      - run: git push origin develop --tags --no-verify
